### ISSUE TITLE
Increase ADB connection timeout

### ISSUE THREAD

**Issue by AndreasSchmid1** [regaw-leinad/AndroidLib#29]
First, thank you for this great lib!
Ist it possible to increase the ADB connection timeout with your lib? 
Like described in this post. http://stackoverflow.com/questions/10795914/android-timeout-error

**Comment by SimonCahill** [comment]
See: https://github.com/regaw-leinad/AndroidLib/blob/master/AndroidLib/Classes/AndroidController/Adb.cs

By calling Adb.FormAdbCommand("cmd", "arg0", "arg1", ...).WithTimeout(millis) you can effectively alter the timeout.
